repos:
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint database_management
      language: python
      types:
        - python
    - id: black
      name: black
      entry: poetry run black .
      language: python
      types:
        - python